### ISSUE TITLE
ModuleNotFoundError: No module named 'battlecode.linux._bc'

### ISSUE THREAD

**Issue by wizzup** [battlecode/bc18-scaffold#19]
~~~~
$ ./run_nodocker.sh 
=== STARTING THE MANAGER (no docker) ===
=== ensuring dependencies ===
$ python3 /data/works/coding_challenges/battlecode-2018/resources/bc18-scaffold/battlecode-manager/gui.py
Traceback (most recent call last):
  File "/data/works/coding_challenges/battlecode-2018/resources/bc18-scaffold/battlecode-manager/gui.py", line 3, in <module>
    import battlecode_cli as cli
  File "/data/works/coding_challenges/battlecode-2018/resources/bc18-scaffold/battlecode-manager/battlecode_cli.py", line 13, in <module>
    import server
  File "/data/works/coding_challenges/battlecode-2018/resources/bc18-scaffold/battlecode-manager/server.py", line 18, in <module>
    import battlecode as bc
  File "/data/works/coding_challenges/battlecode-2018/resources/bc18-scaffold/battlecode/python/battlecode/__init__.py", line 11, in <module>
    from .linux._bc import ffi as _ffi
ModuleNotFoundError: No module named 'battlecode.linux._bc'
~~~~

I think `__init__.py` expects to found `_bc.py` but the `linux` directory is empty

~~~~
$ tree battlecode/python/battlecode/
battlecode/python/battlecode/
├── darwin
│   └── _bc.abi3.so
├── docs.txt
├── __init__.py
├── linux
├── __pycache__
│   └── __init__.cpython-36.pyc
└── win32
    └── _bc.pyd

4 directories, 5 files
~~~~

The same error happened when running `battlecode.sh` too.

**Comment by wizzup** [comment]
Update: I manage to fix the error by copy `_bc.abi3.so` manually build from [battlecode-2018](https://github.com/battlecode/battlecode-2018/tree/master/bindings/python) to `battlecode/python/battlecode/linux`

**Comment by Paul-Andre** [comment]
This is probably related: there's no linux version in the battlecode/c/lib folder. Was the linux build step skipped for some reason?

**Comment by wizzup** [comment]
Problem is no longer exists.
